### ISSUE TITLE
not able to visualize anything on rviz after launching ndt_mapping.launch

### ISSUE THREAD

**Issue by abhishekt711** [rsasaki0109/lidar_localizer#13] opened 2023-04-05 10:41 UTC
after launching the ndt_mapping.launch file. i play my rosbag file having data from velodyne lidar. it is not making map and /ndt_map topic doesn't publish any data after doing rostopic echo /ndt_map.
![Screenshot from 2023-04-05 16-08-26](https://user-images.githubusercontent.com/36338604/230057651-ca49fb8c-7643-4381-8889-d734bb054a6b.png)

**Comment by abhishekt711** [comment] 2023-04-05 17:04
Now it is constructing the map but the point cloud matching is miss aligned and map constructed is not proper
![Screenshot from 2023-04-05 22-32-19](https://user-images.githubusercontent.com/36338604/230152528-60e05b26-da0f-47c8-a145-e8c68db7b08f.png)

**Comment by rsasaki0109** [comment] 2023-04-05 17:10
The following parameters are too large for indoor use and should be adjusted.

`ndt_res`
https://github.com/rsasaki0109/lidar_localizer/blob/main/src/ndt_mapping.cpp#L35
`voxel_leaf_size`
https://github.com/rsasaki0109/lidar_localizer/blob/main/src/ndt_mapping.cpp#L37

Reference
https://github.com/rsasaki0109/pcl_localization_ros2/issues/21#issuecomment-1491135700

**Comment by abhishekt711** [comment] 2023-04-05 17:39
I have kept all the values of ndt_res and voxel_leaf_size mentioned above. but map alignment is not correct. a;lso i have tested for outdoor data it didnt worked. the map in outdoor data is shown below: any other solution?
![Screenshot from 2023-04-05 23-06-07](https://user-images.githubusercontent.com/36338604/230159552-27fc42e2-4da7-4d7b-acf7-f198b3e54c96.png)

in the static transform in launch file this value for tx, ty, tz and r p y is given. do i need to change this?

node pkg="tf" type="static_transform_publisher" name="velodyne_transform_publisher" args="1.2 0 2.0 0 0 0 /base_link /velodyne 10"

**Comment by rsasaki0109** [comment] 2023-04-05 23:43
I think the speed and tf are fine.
Can you send me a video of the terminal output?

**Comment by rsasaki0109** [comment] 2023-04-06 01:16
If you provide rosbag to me, I can check it out.

**Comment by abhishekt711** [comment] 2023-04-06 03:58
please find the link of video of terminal, map is visualized after 32 sec for ndt_res=2, leaf size=0.5
https://drive.google.com/file/d/1GQbAsjzV4y66sIAz6aTqZjiYHifllpgN/view?usp=sharing
Please find the link of bag file: https://drive.google.com/file/d/1QcZzznbOiShLSR2iyaEPrctI5wUtTTCp/view?usp=sharing

**Comment by rsasaki0109** [comment] 2023-04-07 02:22
I think the problem is probably the map update.
I can't work on lidar_localizar right now because I think it's a bug that can't be solved right away. I may work on it further someday.

[Other packages I have developed ](https://github.com/rsasaki0109/lidarslam_ros2)have generated maps without problems.
![image](https://user-images.githubusercontent.com/18298605/230526390-2e60f76f-e31f-4c29-aca2-c55c6b5c6994.png)

**Comment by rsasaki0109** [comment] 2023-07-19 08:07
Since there are no activities, I will close this issue for now. If there is anything else, please reopen this issue.

**Closed by rsasaki0109** 2023-07-19 08:07 UTC
Labels: question
